version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-test: 
    executor:     
      name: node/default
      tag: 14.15.4
    steps:   
      - checkout  
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
          name: Build the library
      - run:
          command: yarn run jest
          name: Run tests
  lint: 
    executor:     
      name: node/default
      tag: 14.15.4
    steps:   
      - checkout  
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Run linting
workflows:
  build-test-lint:
    jobs:
      - build-test
      - lint
    

